version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
  wordpress:
    image: 'wordpress-modphp'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - wordpress_data:/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      # - WORDPRESS_DB_PASSWORD=password
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
