apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-nginx" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
data:
  server-block.conf: |-
    server {
        # Port to listen on, can also be set in IP:PORT format
        listen 8080 default_server;

        root /wordpress;

        # Catch-all server block
        # See: https://nginx.org/en/docs/http/server_names.html#miscellaneous_names
        server_name _;

        location / {
          try_files $uri $uri/index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass   {{ printf "%s-fpm" (include "common.names.fullname" $) }}:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $request_filename;
            include        fastcgi_params;
        }
    }
