apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-nginx" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.nginx.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.service.nginx.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.nginx.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.nginx.type }}
  {{- if and .Values.service.nginx.clusterIP (eq .Values.service.nginx.type "ClusterIP") }}
  clusterIP: {{ .Values.service.nginx.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.service.nginx.type "LoadBalancer") (eq .Values.service.nginx.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.nginx.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if (and (eq .Values.service.nginx.type "LoadBalancer") .Values.service.nginx.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if (and (eq .Values.service.nginx.type "LoadBalancer") (not (empty .Values.service.nginx.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.nginx.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.nginx.port }}
      protocol: TCP
      targetPort: http
      {{- if (and (or (eq .Values.service.nginx.type "NodePort") (eq .Values.service.nginx.type "LoadBalancer")) (not (empty .Values.service.nginx.nodePorts.http))) }}
      nodePort: {{ .Values.service.nginx.nodePorts.http }}
      {{- else if eq .Values.service.nginx.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: https
      port: {{ .Values.service.nginx.httpsPort }}
      protocol: TCP
      targetPort: {{ .Values.service.nginx.httpsTargetPort }}
      {{- if (and (or (eq .Values.service.nginx.type "NodePort") (eq .Values.service.nginx.type "LoadBalancer")) (not (empty .Values.service.nginx.nodePorts.https))) }}
      nodePort: {{ .Values.service.nginx.nodePorts.https }}
      {{- else if eq .Values.service.nginx.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.service.nginx.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.nginx.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
