apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-fpm" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.phpFpm.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.service.phpFpm.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.phpFpm.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.phpFpm.type }}
  {{- if and .Values.service.phpFpm.clusterIP (eq .Values.service.phpFpm.type "ClusterIP") }}
  clusterIP: {{ .Values.service.phpFpm.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.service.phpFpm.type "LoadBalancer") (eq .Values.service.phpFpm.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.phpFpm.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if (and (eq .Values.service.phpFpm.type "LoadBalancer") .Values.service.phpFpm.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if (and (eq .Values.service.phpFpm.type "LoadBalancer") (not (empty .Values.service.phpFpm.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.phpFpm.loadBalancerIP }}
  {{- end }}
  ports:
    - name: fastcgi
      port: {{ .Values.service.phpFpm.port }}
      protocol: TCP
      targetPort: 9000
      {{- if (and (or (eq .Values.service.phpFpm.type "NodePort") (eq .Values.service.phpFpm.type "LoadBalancer")) (not (empty .Values.service.phpFpm.nodePort))) }}
      nodePort: {{ .Values.service.phpFpm.nodePort }}
      {{- else if eq .Values.service.phpFpm.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.service.phpFpm.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.phpFpm.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
