version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
  nginx:
    image: 'docker.io/bitnami/nginx:1.19-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - wordpress
    volumes:
      - ./server_blocks/wordpress.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress.conf
      # WordPress data files
      - wordpress_data:/wordpress
  wordpress:
    image: 'wordpress-php-fpm'
    volumes:
      - wordpress_data:/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      # - WORDPRESS_DB_PASSWORD=password
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
